#' @export
set.field.types <- function(x){
  
  x$associated_specimens <- as.character(x$associated_specimens)
  x$associated_taxa <- as.character(x$associated_taxa)
  x$catalognum <- as.character(x$catalognum)
  x$class <- as.character(x$class)
  x$collection_event_id <- as.character(x$collection_event_id)
  x$collectionnotes <- as.character(x$collectionnotes)
  x$collectiontime <- as.character(x$collectiontime)
  x$collectors <- as.character(x$collectors)
  x$country <- as.character(x$country)
  x$depth <- as.numeric(x$depth)
  x$depth_accuracy <- as.character(x$depth_accuracy)
  x$elev <- as.numeric(x$elev)
  x$elev_accuracy <- as.character(x$elev_accuracy)
  x$extrainfo <- as.character(x$extrainfo)
  x$family <- as.character(x$family)
  x$fieldnum <- as.character(x$fieldnum)
  x$genus <- as.character(x$genus)
  # x$gps_accuracy_units <- as.character(x$gps_accuracy_units)
  x$gps_source <- as.character(x$gps_source)
  x$habitat <- as.character(x$habitat)
  x$identification_method <- as.character(x$identification_method)
  x$identifier_fullname <- as.character(x$identifier_fullname)
  x$inst_name <- as.character(x$inst_name)
  x$lat <- as.numeric(x$lat)
  x$lifestage <- as.character(x$lifestage)
  x$long <- as.numeric(x$long)
  x$note <- as.character(x$note)
  x$order <- as.character(x$order)
  x$phylum <- as.character(x$phylum)
  x$processid <- as.character(x$processid)
  x$province <- as.character(x$province)
  x$record.code <- as.character(x$record.code)
  x$region <- as.character(x$region)
  x$reproduction <- as.character(x$reproduction)
  x$sampleid <- as.character(x$sampleid)
  x$sampling_protocol <- as.character(x$sampling_protocol)
  x$sector <- as.character(x$sector)
  # x$seqid <- as.numeric(x$seqid)
  x$sex <- as.character(x$sex)
  x$site <- as.character(x$site)
  x$sitecode <- as.character(x$sitecode)
  x$species <- as.character(x$species)
  x$specimenid <- as.numeric(x$specimenid)
  x$subfamily <- as.character(x$subfamily)
  x$subspecies <- as.character(x$subspecies)
  x$taxnotes <- as.character(x$taxnotes)
  x$taxon <- as.character(x$taxon)
  x$tissuetype <- as.character(x$tissuetype)
  x$uri <- as.character(x$uri)
  x$vouchertype <- as.character(x$vouchertype)
  
  return(x)
  
}